# Generated by Django 4.2.25 on 2025-10-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='sentiment',
            field=models.IntegerField(choices=[(1, 'Positive'), (0, 'Negative')], default=1),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='experience',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='rating',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
